/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sisgeproinv.accesos;

/**
 *
 * @author Alejandro Gonzalez
 */
public class Accesos extends javax.swing.JPanel {

    /**
     * Creates new form Accesos
     */
    public Accesos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegistroEquiposAcceso = new javax.swing.JPanel();
        IconoPrincipal = new javax.swing.JLabel();
        TituloPrincipal = new javax.swing.JLabel();
        IconoSecundario = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        InventarioEquiposAcceso = new javax.swing.JPanel();
        IconoPrincipal1 = new javax.swing.JLabel();
        TituloPrincipal1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(232, 228, 237));

        RegistroEquiposAcceso.setBackground(new java.awt.Color(255, 255, 255));
        RegistroEquiposAcceso.setPreferredSize(new java.awt.Dimension(310, 120));
        RegistroEquiposAcceso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IconoPrincipal.setBackground(new java.awt.Color(37, 216, 250));
        IconoPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sisgeproinv/iconos/agregarB96.png"))); // NOI18N
        IconoPrincipal.setOpaque(true);
        RegistroEquiposAcceso.add(IconoPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 130));

        TituloPrincipal.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        TituloPrincipal.setForeground(new java.awt.Color(27, 30, 33));
        TituloPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloPrincipal.setText("REGISTRAR EQUIPO");
        RegistroEquiposAcceso.add(TituloPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 200, -1));

        IconoSecundario.setBackground(new java.awt.Color(255, 255, 255));
        IconoSecundario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconoSecundario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sisgeproinv/iconos/equipoN48.png"))); // NOI18N
        IconoSecundario.setOpaque(true);
        RegistroEquiposAcceso.add(IconoSecundario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 60, 50));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sisgeproinv/iconos/bateriaN20.png"))); // NOI18N
        jLabel5.setText(">> 23.6% <<");
        RegistroEquiposAcceso.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sisgeproinv/iconos/cpuN20.png"))); // NOI18N
        jLabel6.setText(">> 27.5% <<");
        RegistroEquiposAcceso.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sisgeproinv/iconos/impresoraN20.png"))); // NOI18N
        jLabel7.setText(">> 14.8% <<");
        RegistroEquiposAcceso.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        InventarioEquiposAcceso.setBackground(new java.awt.Color(255, 255, 255));
        InventarioEquiposAcceso.setPreferredSize(new java.awt.Dimension(310, 120));
        InventarioEquiposAcceso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IconoPrincipal1.setBackground(new java.awt.Color(255, 51, 102));
        IconoPrincipal1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconoPrincipal1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sisgeproinv/iconos/inventarioB96.png"))); // NOI18N
        IconoPrincipal1.setOpaque(true);
        InventarioEquiposAcceso.add(IconoPrincipal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 130));

        TituloPrincipal1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        TituloPrincipal1.setForeground(new java.awt.Color(27, 30, 33));
        TituloPrincipal1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloPrincipal1.setText("INVENTARIO EQUIPOS");
        InventarioEquiposAcceso.add(TituloPrincipal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 200, -1));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(49, 75, 212));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sisgeproinv/iconos/equipoN20.png"))); // NOI18N
        jLabel1.setText("EQUIPOS ACTIVOS");
        InventarioEquiposAcceso.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("85.7%");
        InventarioEquiposAcceso.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, 20));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(219, 38, 79));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sisgeproinv/iconos/equipoN20.png"))); // NOI18N
        jLabel3.setText("EQUIPOS INACTIVOS");
        InventarioEquiposAcceso.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("14.3%");
        InventarioEquiposAcceso.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(RegistroEquiposAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(InventarioEquiposAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RegistroEquiposAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InventarioEquiposAcceso, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                .addContainerGap(458, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IconoPrincipal;
    private javax.swing.JLabel IconoPrincipal1;
    private javax.swing.JLabel IconoSecundario;
    public javax.swing.JPanel InventarioEquiposAcceso;
    public javax.swing.JPanel RegistroEquiposAcceso;
    private javax.swing.JLabel TituloPrincipal;
    private javax.swing.JLabel TituloPrincipal1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
